FROM        redhat/ubi9
COPY        db/mongo.repo /etc/yum.repos.d/mongo.repo
RUN         dnf install mongodb-mongosh -y
RUN         mkdir /app
WORKDIR     /app
COPY        db/ /app/
ENTRYPOINT  ["bash", "run.sh"]
#ENTRYPOINT  ["tail", "-f","/dev/null"]

