name: Docker Build - DB Load
on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: http://vault-int.rdevopsb84.online:8200/
          token: ${{ secrets.vault_token }}
          secrets: |
            roboshop-infra/data/azure-sp ARM_CLIENT_ID | ARM_CLIENT_ID ;
            roboshop-infra/data/azure-sp ARM_CLIENT_SECRET | ARM_CLIENT_SECRET ;
            roboshop-infra/data/azure-sp ARM_TENANT_ID | ARM_TENANT_ID ;
            roboshop-infra/data/azure-sp ARM_SUBSCRIPTION_ID | ARM_SUBSCRIPTION_ID ;
            roboshop-infra/data/sonarqube token | SONAR_TOKEN ;

      - name: Docker Build
        run: |
          az login --service-principal --username "${ARM_CLIENT_ID}" --password "${ARM_CLIENT_SECRET}" --tenant "${ARM_TENANT_ID}"
          az acr login --name roboshopb84
          docker build -t roboshopb84.azurecr.io/roboshop-catalogue-db-job:latest -f Dockerfile-dbjob .
          docker push roboshopb84.azurecr.io/roboshop-catalogue-db-job:latest
